apiVersion: v1
kind: PersistentVolume
metadata:
  name: may-volume
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    drive: efs.csi.aws.com
    volumeHandle: {{ .Values.efs.volumeHandle }}
