version: '3'

services: 

  elasticsearch: 
    container_name: es-test
    image: elasticsearch:7.12.1
    ports:
      - 9200:9200
      - 9300:9300
    networks: 
      - net-test
    volumes: 
      - /var/es/data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - TZ=Asia/Seoul
    user: root
    restart: always
    privileged: true
  
  kibana:
    container_name: kibana
    image: kibana:6.8.18
    ports:
      - 5601:5601
    networks: 
      - net-test
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    environment:
      - TZ:Asia/Seoul
    restart: always
    privileged: true

networks: 
  net-test:
    driver: bridge
