apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
rules:
  - verbs:
      - create
      - delete
      - get
      - patch
    apiGroups:
      - apps
    resources:
      - deployments
      - pods
