apiversion: v1
kind: Secret
metadata: 
  name: {{ .Values.token }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.name }}
type: kubernetes.io/service-account-token
