apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-may
  region: ap-northeast-2
  version: "1.24"

vpc:
  cidr: "10.0.0.0/16"

managedNodeGroups:
  - name: may-node
    instanceType: t4g.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    iam:
      withAddonPolicies:
        imageBuilder: true
        albIngress: true
        awsLoadBalancerController: true
        cloudWatch: true
        autoscaler: true
        ebs: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

iam:
  withOIDC: true