apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.initial.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.initial.label }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.initial.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.initial.servicePort }}
      targetPort: {{ .Values.initial.port }}
      nodePort: {{ .Values.initial.nodePort }}
