apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonly-role-binding
  namespace: dev
subjects: # kind: Group?
- kind: User
  name: readonly-innfi
roleRef:
  kind: Role
  name: readonly-role
  apiGroup: rbac.authorization.k8s.io
