service: nest-lambda-serverless

plugins:
  - serverless-jetpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /

custom:
  serverless-offline:
    useDocker: true
    noTimeout: true
    reloadHandler: true
