---
- hosts: starter_host
  become: yes
  user: ec2-user

  tasks:
    - name: ping
      ping:
      remote_user: ec2

    - name: yum update
      yum: name=* state: latest

# login to aws via user credential
    - name: login
      ansible.builtin.shell:
      aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin (aws sts get-caller-identity|jq .Account -r).dkr.ecr.ap-northeast-2.amazonaws.com     

# pull image
    - name: pull image from ECR
      community.docker.docker_image:
        name: (aws sts get-caller-identity|jq .Account -r).dkr.ecr.ap-northeast-2.amazonaws.com/starter
        source: pull

# remove, pull, start the container
    - name: remove container
      community.docker.docker_container:
        name: starter
        state: absent

    - name: pull image and start
      community.docker.docker_container:
        name: starter
        image: (aws sts get-caller-identity|jq .Account -r).dkr.ecr.ap-northeast-2.amazonaws.com/starter:latest
        state: present

# stop and remove existing container with image

# start a new container

# check connectivity
