apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-admin
  namespace: dev
rules:
- apigroups: ["*"]
  resources: ["services", "deployments", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
