apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-cluster-info
  namespace: amazon-cloudwatch
data:
  cluster.name: cluster-may
  http.port: '2020'
  http.server: 'On'
  logs.region: ap-northeast-2
  read.head: 'Off'
  read.tail: 'On'
