apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: dev
rules:
  [
    {
      apiGroups: ['*'],
      resources: [
        'services',
        'deployments',
        'pods',
        'pods/log',
        'pods/exec',
        'configmaps',
        'secrets',
        'ingresses',
        'ingressClasses',
        'serviceaccounts',
        'horizontalpodautoscalers'
      ],
      verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete']
    }
  ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manager-role-binding
  namespace: dev
subjects:
- kind: User
  name: dev-user
roleRef:
  kind: Role
  name: manager-role
  apiGroup: rbac.authorization.k8s.io