apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reader-role
  namespace: dev
rules:
  [
    {
      apiGroups: ['*'],
      resources: [
        'services',
        'deployments',
        'pods',
        'pods/log',
        'pods/exec',
        'configmaps',
      ],
      verbs: ['get', 'list', 'watch']
    }
  ]
