apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reader-role
  namespace: dev
rules:
  [
    {
      apiGroups: ['*'],
      resources: [
        'services',
        'deployments',
        'pods',
        'pods/log',
        'pods/exec',
        'configmaps',
      ],
      verbs: ['get', 'list', 'watch']
    }
  ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reader-role-binding
  namespace: dev
subjects:
- kind: User
  name: readonly
roleRef:
  kind: Role
  name: reader-role
  apiGroup: rbac.authorization.k8s.io